### ISSUE TITLE
tico dir does not exist in demo\index.php

### ISSUE THREAD

**Issue by andymnc** [foo123/LoginManager#1]
There's an error in the index.php of the demo dir. At line 4 you can see:
`include(ROOT.'/../../tico/tico/Tico.php');`
but the tico dir is not anywhere in the whole project

**Comment by foo123** [comment]
This is not an error. It would be overhead to include tico repo in this simply for a demo.
The demo uses my own local repo of Tico. 
Download your local copy of Tico repo and update the path in the demo to point to that location.
